### ISSUE TITLE
Release builds

### ISSUE THREAD

**Issue by shuklaayush** [roynalnaruto/solc-builds#1]
Consider building binaries with the `-DCMAKE_BUILD_TYPE=Release` flag to maintain parity with https://binaries.soliditylang.org

pre-release builds have lower precedence in SemVer than released versions and lead to weird compilation errors

![telegram-cloud-photo-size-5-6147487107556421270-y](https://user-images.githubusercontent.com/27727946/157646194-677c778f-567d-408f-ba08-caba3033680e.jpg)

**Comment by peetzweg** [comment]
Related: https://github.com/gakonst/foundry/issues/892
Hope this can be fixed asap. 🙃

**Comment by roynalnaruto** [comment]
Updated builds here: https://github.com/roynalnaruto/solc-builds/commit/d1388e554684c5a10954d0c80182e671c4fc2ade
Updated `svm-rs` here: https://github.com/roynalnaruto/svm-rs/commit/76a9779c1985ca39192f8254494d72f5802602df
