### ISSUE TITLE
Retire this repo

### ISSUE THREAD

**Issue by sambacha** [roynalnaruto/solc-builds#13]
solc now provides universal binaries: https://github.com/ethereum/solidity/issues/14813 as of 0.8.24 (at least).

**Comment by mattsse** [comment]
unable to find them, no idea where they're made available under https://binaries.soliditylang.org

EDIT:

ah they're universal now, so I can just use macosx-adm64 I guess

**Comment by zerosnacks** [comment]
Looks like this repo is still required to be active given that `solc` only has universal builds >= `0.8.24` and no immediate intention of providing builds for prior versions, see https://github.com/ethereum/solidity/issues/12291#issuecomment-1976754020
