### ISSUE TITLE
Getting TCP connect error when requesting list.json

### ISSUE THREAD

**Issue by alfheimrShiven** [roynalnaruto/solc-builds#7]
I'm getting the following error on running `forge build` on [this repo](https://github.com/thirdweb-dev/contracts)

```zsh
Error: 
error sending request for url (https://raw.githubusercontent.com/alloy-rs/solc-builds/55ef6c89b8a09c16feee4a424f8a53f822831a61/macosx/aarch64/list.json): error trying to connect: tcp connect error: Operation timed out (os error 60)
```
Not sure how to solve this. Any help would be appreciated. Thanks!

**Comment by alfheimrShiven** [comment]
@mattsse could you help here, please? Thanks.

**Comment by mattsse** [comment]
hmm this just looks like a network issue.

you can also use --offline to only use already downloaded solc versions

**Comment by alfheimrShiven** [comment]
Sorry @mattsse but that doesn't seem to be the case. I have a stable internet connection.

On trying the `--offline` flag, I'm getting the following error: 
`can't install missing solc 0.8.21 in offline mode`

**Comment by mattsse** [comment]
are able to curl the url?

**Comment by alfheimrShiven** [comment]
Getting the following response @mattsse :
 `Failed to connect to raw.githubusercontent.com port 443 after 75233 ms: Couldn't connect to server`

**Comment by alfheimrShiven** [comment]
This issue was due to my network provider's DNS had blocked `raw.githubusercontent.com`
I had to switch my DNS provider from my network provider's DNS to Google's `8.8.4.4`
